import 'dart:convert';
import 'package:path/path.dart' as p;
import 'package:sqflite/sqflite.dart';
class AppDatabase {
  static const version = 4; Database? _db; Database get db => _db!;
  Future<void> open() async { final dir=await getDatabasesPath(); _db=await openDatabase(p.join(dir,'field_sales.db'),version:version,onCreate:(db,_)=>_createV4(db),onUpgrade:_upgrade); }
  Future<void> _createV4(Database db) async { await db.execute('CREATE TABLE sync_queue (id INTEGER PRIMARY KEY AUTOINCREMENT, entity_type TEXT NOT NULL, entity_uuid TEXT NOT NULL, action TEXT NOT NULL, payload TEXT NOT NULL, priority INTEGER NOT NULL DEFAULT 100, attempts INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL DEFAULT 10, status TEXT NOT NULL DEFAULT "pending", error_message TEXT, next_retry_at TEXT, server_id INTEGER, server_uuid TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)'); await db.execute('CREATE INDEX idx_sync_status_priority ON sync_queue(status,priority,created_at)'); await db.execute('CREATE INDEX idx_sync_entity ON sync_queue(entity_type,entity_uuid)');
    await db.execute('CREATE TABLE local_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)'); await db.execute('CREATE TABLE local_sync_log (id INTEGER PRIMARY KEY AUTOINCREMENT, level TEXT, message TEXT, created_at TEXT NOT NULL)'); await db.execute('CREATE TABLE local_products (id INTEGER PRIMARY KEY, payload TEXT NOT NULL, cached_at TEXT NOT NULL)');
    for(final name in ['customers','territories','routes','route_customers','products','price_lists','price_list_items']) { await db.execute('CREATE TABLE $name (id INTEGER PRIMARY KEY, uuid TEXT, payload TEXT NOT NULL, cached_at TEXT NOT NULL)'); }
    await db.execute('CREATE TABLE session_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)');
    await db.execute('CREATE TABLE local_work_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, offline_uuid TEXT NOT NULL UNIQUE, server_id INTEGER, date TEXT NOT NULL, start_time TEXT NOT NULL, end_time TEXT, start_latitude REAL NOT NULL, start_longitude REAL NOT NULL, start_accuracy REAL NOT NULL, end_latitude REAL, end_longitude REAL, end_accuracy REAL, status TEXT NOT NULL, sync_status TEXT NOT NULL, start_source TEXT NOT NULL DEFAULT "manual", privacy_ack_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)');
    await db.execute('CREATE UNIQUE INDEX one_active_session ON local_work_sessions(status) WHERE status="active"');
    await db.execute('CREATE TABLE local_gps_points (id INTEGER PRIMARY KEY AUTOINCREMENT, client_uuid TEXT NOT NULL UNIQUE, latitude REAL NOT NULL, longitude REAL NOT NULL, altitude REAL, accuracy REAL NOT NULL, speed REAL, heading REAL, battery_level INTEGER, is_charging INTEGER NOT NULL DEFAULT 0, network_status TEXT, is_mock_location INTEGER NOT NULL DEFAULT 0, provider TEXT, recorded_at TEXT NOT NULL, sequence_number INTEGER NOT NULL, batch_uuid TEXT, sync_status TEXT NOT NULL DEFAULT "pending", last_error TEXT, uploaded_at TEXT, created_at TEXT NOT NULL)');
    await db.execute('CREATE INDEX idx_gps_pending ON local_gps_points(sync_status,id)'); await db.execute('CREATE INDEX idx_gps_recorded ON local_gps_points(recorded_at)');
    await db.execute('CREATE TABLE privacy_acknowledgements (id INTEGER PRIMARY KEY AUTOINCREMENT, policy_version TEXT NOT NULL, acknowledged_at TEXT NOT NULL, user_id TEXT, tenant_id TEXT, device_id TEXT, app_version TEXT NOT NULL, sync_status TEXT NOT NULL DEFAULT "pending", server_id INTEGER, server_uuid TEXT, UNIQUE(policy_version,user_id,tenant_id,device_id))');
  }
  Future<bool> _hasColumn(Database db,String table,String column) async => (await db.rawQuery('PRAGMA table_info($table)')).any((r)=>r['name']==column);
  Future<void> _upgrade(Database db,int old,int next) async { if(old<4){ final tables=(await db.rawQuery("SELECT name FROM sqlite_master WHERE type='table'")).map((x)=>x['name']).toSet(); if(!tables.contains('local_work_sessions')) { await _createV4(db); return; } if(!await _hasColumn(db,'local_work_sessions','start_source')) await db.execute('ALTER TABLE local_work_sessions ADD COLUMN start_source TEXT NOT NULL DEFAULT "manual"'); if(!tables.contains('local_gps_points')) { await db.execute('CREATE TABLE local_gps_points (id INTEGER PRIMARY KEY AUTOINCREMENT, client_uuid TEXT NOT NULL UNIQUE, latitude REAL NOT NULL, longitude REAL NOT NULL, altitude REAL, accuracy REAL NOT NULL, speed REAL, heading REAL, battery_level INTEGER, is_charging INTEGER NOT NULL DEFAULT 0, network_status TEXT, is_mock_location INTEGER NOT NULL DEFAULT 0, provider TEXT, recorded_at TEXT NOT NULL, sequence_number INTEGER NOT NULL, batch_uuid TEXT, sync_status TEXT NOT NULL DEFAULT "pending", last_error TEXT, uploaded_at TEXT, created_at TEXT NOT NULL)'); await db.execute('CREATE INDEX idx_gps_pending ON local_gps_points(sync_status,id)'); await db.execute('CREATE INDEX idx_gps_recorded ON local_gps_points(recorded_at)'); } if(!tables.contains('privacy_acknowledgements')) await db.execute('CREATE TABLE privacy_acknowledgements (id INTEGER PRIMARY KEY AUTOINCREMENT, policy_version TEXT NOT NULL, acknowledged_at TEXT NOT NULL, user_id TEXT, tenant_id TEXT, device_id TEXT, app_version TEXT NOT NULL, sync_status TEXT NOT NULL DEFAULT "pending", server_id INTEGER, server_uuid TEXT, UNIQUE(policy_version,user_id,tenant_id,device_id))'); } }
  Future<void> setting(String key,Object value)=>db.insert('local_settings',{'key':key,'value':jsonEncode(value)},conflictAlgorithm:ConflictAlgorithm.replace);
  Future<dynamic> readSetting(String key) async { final rows=await db.query('local_settings',where:'key=?',whereArgs:[key],limit:1);return rows.isEmpty?null:jsonDecode(rows.first['value'] as String); }
}
